### ISSUE TITLE
Newlines in help text lost in web client

### ISSUE THREAD

**Issue by dreeves** [dreeves/omnibot#126]
## Replicata

1. Go to https://omnibot.yootl.es
2. Type /bid help

## Expectata

Readable help text.

## Resultata

Newlines are stripped out:

![image](https://user-images.githubusercontent.com/9928/230753427-70427a54-c44f-4804-b8b9-6455d68103a5.png)

_**Verbata**: formatting, newlines, readability,_

**Comment by dreeves** [comment]
I've tentatively fixed this by just sending each line as a separate message. There may be a much simpler/cleaner way to do it though.

After shot:

![image](https://github.com/dreeves/omnibot/assets/9928/f8154916-c90f-4b10-84d8-f63f4b3a4d5c)

**Comment by jakecoble** [comment]
Added a cleaner, more complete solution here https://github.com/dreeves/omnibot/pull/156 . This PR also preserves other whitespace formatting, such as tabs.
