### ISSUE TITLE
Refactor command API

### ISSUE THREAD

**Issue by jakecoble** [dreeves/omnibot#139]
- [x] change inputs and outputs to execute as follows:

```
{cid, sender, input} --> {output, voxmode}
```

- [ ] pass in the channel name
- [ ] pass in the platform name

**Comment by dreeves** [comment]
Is it pretty straightforward to add channel name and platform name to the list of inputs?

**Comment by dreeves** [comment]
Check out the new /omninom command which is handy for testing slash commands in general and also for things like what inputs are passed to slash commands:

ME: /omninom test2301
OMNIBOT:
> This is Omnibot v2023.05.12-j called by @dreev in channel discord_847897704632942632.
> You called /omninom with arg1 = "test2301".
> Debugging factoid: If arg1 had leading or trailing whitespace, it got trimmed before Omnibot saw it.

I think it would be good for the business logic to know the actual channel name.

**Comment by dreeves** [comment]
Did you add platform yet?

**Comment by jakecoble** [comment]
> Did you add platform yet?

Yes. That's passed in as `platform`, which can currently be either 
`"discord"` or `"slack"`.
