### ISSUE TITLE
Clarify if input to commands is trimmed

### ISSUE THREAD

**Issue by jakecoble** [dreeves/omnibot#150]

**Comment by dreeves** [comment]
> guarantee that input to commands is trimmed

Or first just decide: should that happen outside the business logic? I was just wondering if the business logic should do its own trim or if it should trust that the input is already trimmed.

Doesn't seem like it matters much but if I had to choose, let's say business logic gets the raw string the user typed and any cleanup, including trimming, is the responsibility of the business logic.
