### ISSUE TITLE
Echo my bid to just me

### ISSUE THREAD

**Issue by dreeves** [dreeves/omnibot#153]
## Replicata

1. Start an auction with `/bid test auction with @alice`
2. Submit your own bid with `/bid this is my bid`

## Expectata

No one else sees my bid yet _but I do_.

## Resultata

No one sees my bid, not even me.

This happens in both Discord and Slack.

## Cognata

* #132 

_**Verbata**: voxmode, seeing your own bid,_

**Comment by jakecoble** [comment]
Already works on the latest commit on master
