### ISSUE TITLE
Verify that setting `required: true` on commands works without error

### ISSUE THREAD

**Issue by jakecoble** [dreeves/omnibot#157]
We got a "command is outdated" error from Discord after setting `required: true` in `roll.js`.

**Comment by jakecoble** [comment]
Setting `required: true` appears to function correctly. Maybe this should be labeled `cnr` instead? Your call.

**Comment by dreeves** [comment]
Yeah, I'm pretty confused what was going on when I tried changing this for the /roll command before. Lemme experiment a bit more before closing this.

We now have the /omninom slash command which is better for testing.
