### ISSUE TITLE
Make a dispatcher

### ISSUE THREAD

**Issue by dreeves** [dreeves/omnibot#165]
Currently app.js is pretty confusing, mixing together a lot of setup code with some business logic. I'd like to separate out the following business logic:

1. Omnibot's decision about what channels to pay attention to
2. The regexes Omnibot uses to decide what to reply to

I'd also like to abstract away the concept of slash commands.

There should be a single dispatcher function that receives every message and decides what to do with it. Currently that includes something like the following:

1. If the channel is #games or #spellingbee or matches #lexi.* and the message is a single word consisting of only letters then feed the message to lexiguess
2. If the message starts with "/bid" then feed it to bid.js
3. If the message starts with "/roll" then feed it to roll.js
4. If the message starts with "/omninom" then feed it to omninom.js
5. If the message at-mentions omnibot then... TBD
6. Otherwise, ignore it.

I'm thinking the business logic shouldn't even understand the concept of slash commands at all. From the business logic's point of view, messages just come in as strings, some of which may happen to start with a slash character, and the dispatcher passes those messages to the appropriate submodule, all based purely on regexes.

PS: And of course we want it to be easy to add new rules/regexes to that list. And maybe webhooks (#159) can also be in that list. Hitting the webhook is treated the same as any other incoming message for the bot.

**Comment by dreeves** [comment]
Also there's DM'ing the bot. I'd like to capture all of these things in a nice general, flexible architecture. Proposal: Every incoming message that Omnibot is allowed to see hits the dispatcher as a hash like so:

* `plat` = a string like "discord" or "slack" saying what platform we're on, which we generally expect the business logic to not care about
* `chan` = the channel that the message was sent in, eg, "botspam" or "games" or "DM" (and maybe this is actually 2 parameters, for channel name and channel ID, but we have no use case for caring about the channel ID so far)
* `user` = the username of whoever is sending this message
* `mesg` = the actual string that the user typed, eg, "/bid my bid is $12"
* `msid` = the message ID that the platform assigned to the user's message, which will be null if it's not an actual message in the channel, as it won't be if the user sent it by invoking a slash command, for example
* `priv` = whether the message was sent to Omnibot privately which is the case if it was DM'd, is sent as a webhook, or sent by invoking a slash command
* `rfun` = a reply function that the business logic uses to send its reply

And `rfun` itself takes the following parameters:

* `plat` = the platform, typically whatever `plat` was specified in the incoming message but maybe we'll make some sort of Slack/Discord bridge, who knows.
* `chan` = the channel to send to
* `user` = the username of who we're sending this to
* `mesg` = the text of the message to send
* `priv` = whether we're sending this privately to the recipient, eg, replying to a slash command in whisper mode

The `rfun` function returns the message ID of the sent message. (Maybe Javascript promises is the right way to implement that?)

Here's a review of how the above captures what we previously did with voxmode:

* WHISP = {whisper in, whisper out} = Incoming message is private and the bot whispers its reply back. E.g., acknowledging a new sealed bid.
* HOLLA = {whisper in, holler out with echoing} = Incoming message is private but the bot echoes it publicly as part of its reply. E.g., kicking off a new auction with /bid.
* BLURT = {whisper in, holler out without echoing} = Incoming message has is private and the bot doesn't echo it but just sends a separate reply. E.g., getting the final sealed bid and announcing the auction results.
* NORML = {holler in, holler out} = Incoming message is public and the bot does a normal reply to it. E.g., Lexiguess replying to a guess.
* KIBITZ = {holler in, whisper out} = A normal public message from a user that the bot replies to privately, probably as a DM.

**Comment by dreeves** [comment]
PS: Actually now I'm not sure why `rfun` would want to be passed in, rather than just being a separate library function that the business logic can call when it wants to send a message.

PPS: And separately from all that we need a place to store the slash command metadata (description, usage hint, name of argument, whether argument is required).

**Comment by jakecoble** [comment]
"the bot replies to privately, probably as a DM"

Should `priv` mean "reply as DM"?

**Comment by dreeves** [comment]
After discussing on Discord, tentatively the answer is yes. We've got:

`sendmesg(plat, fief, chan, user, mesg, mrid, priv, phem)`

Specifying priv=true and phem=true is an error, presumably, if there's no such thing as an ephemeral DM.
